export const ROLES = {
  EMPLOYEE: 'EMPLOYEE',
  HR_MANAGER: 'HR_MANAGER',
  HR_PAYROLL_USER: 'HR_PAYROLL_USER',
  HR_PAYROLL_MANAGER: 'HR_PAYROLL_MANAGER',
  ADMIN: 'ADMIN',
};

export const ROLE_LABELS = {
  [ROLES.EMPLOYEE]: 'Employee',
  [ROLES.HR_MANAGER]: 'HR Manager',
  [ROLES.HR_PAYROLL_USER]: 'Payroll User',
  [ROLES.HR_PAYROLL_MANAGER]: 'Payroll Manager',
  [ROLES.ADMIN]: 'Administrator',
};

export const PERMISSION_MATRIX = {
  employees: {
    view: [ROLES.EMPLOYEE, ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    create: [ROLES.ADMIN], // Admin-only per matrix
    edit: [ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    delete: [ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    provisionRole: [ROLES.ADMIN],
  },
  contracts: {
    view: [ROLES.EMPLOYEE, ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    create: [ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    edit: [ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    delete: [ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
  },
  schedules: {
    view: [ROLES.EMPLOYEE, ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    create: [ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    edit: [ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    delete: [ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
  },
  attendance: {
    view: [ROLES.EMPLOYEE, ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    create: [ROLES.EMPLOYEE, ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    edit: [ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    delete: [ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
  },
  timeOffTypes: {
    view: [ROLES.EMPLOYEE, ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    create: [ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    edit: [ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    delete: [ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
  },
  timeOffAllocations: {
    view: [ROLES.EMPLOYEE, ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    create: [ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    edit: [ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    delete: [ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
  },
  timeOffRequests: {
    view: [ROLES.EMPLOYEE, ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    create: [ROLES.EMPLOYEE, ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    approve: [ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    edit: [ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    delete: [ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
  },
  salaryStructures: {
    view: [ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    create: [ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    edit: [ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    delete: [ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
  },
  salaryRules: {
    view: [ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    create: [ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    edit: [ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    delete: [ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
  },
  payruns: {
    view: [ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    create: [ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    edit: [ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    delete: [ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN], // HR_PAYROLL_USER cannot delete
  },
  payslips: {
    view: [ROLES.EMPLOYEE, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN], // HR_MANAGER has None
    create: [ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    edit: [ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
    delete: [ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN], // HR_PAYROLL_USER cannot delete
  },
  payrollDashboard: {
    view: [ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
  },
};

// Map exact path route permissions per user role
export const ROUTE_PERMISSIONS = {
  '/employees': [ROLES.EMPLOYEE, ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
  '/contracts': [ROLES.EMPLOYEE, ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
  '/attendance': [ROLES.EMPLOYEE, ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
  '/time-off/dashboard': [ROLES.EMPLOYEE, ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
  '/time-off/requests': [ROLES.EMPLOYEE, ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
  '/time-off/allocations': [ROLES.EMPLOYEE, ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
  '/time-off/types': [ROLES.EMPLOYEE, ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
  '/payroll/dashboard': [ROLES.HR_MANAGER, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
  '/payroll/payruns': [ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
  '/payroll/payslips': [ROLES.EMPLOYEE, ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
  '/payroll/structures': [ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
  '/payroll/rules': [ROLES.HR_PAYROLL_USER, ROLES.HR_PAYROLL_MANAGER, ROLES.ADMIN],
};

export function canAccessModule(role, moduleName) {
  if (!role) return true;
  const normalizedRole = String(role).toUpperCase();
  const permissions = PERMISSION_MATRIX[moduleName];
  if (!permissions || !permissions.view) return true;
  return permissions.view.includes(normalizedRole);
}

export function canAccessPath(role, path) {
  if (!role) return true;
  const normalizedRole = String(role).toUpperCase();
  const allowedRoles = ROUTE_PERMISSIONS[path];
  if (!allowedRoles) return true;
  return allowedRoles.includes(normalizedRole);
}

export function canPerformAction(role, moduleName, action = 'view') {
  if (!role) return false;
  const normalizedRole = String(role).toUpperCase();
  const modulePermissions = PERMISSION_MATRIX[moduleName];
  if (!modulePermissions || !modulePermissions[action]) return false;
  return modulePermissions[action].includes(normalizedRole);
}

